import { SlashCommandBuilder, PermissionFlagsBits } from 'discord.js';
import { leonisEmbed, COLORS } from '../systems/embeds.js';
export const adminCommands=[
 {data:new SlashCommandBuilder().setName('limpar').setDescription('Apaga mensagens.').setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages).addIntegerOption(o=>o.setName('quantidade').setDescription('1 a 100').setRequired(true).setMinValue(1).setMaxValue(100)),async execute(i){const n=i.options.getInteger('quantidade',true);const deleted=await i.channel.bulkDelete(n,true);await i.reply({embeds:[leonisEmbed({title:'🧹 Limpeza concluída',description:`Foram apagadas **${deleted.size}** mensagens.`,color:COLORS.success})],ephemeral:true})}},
 {data:new SlashCommandBuilder().setName('trancar').setDescription('Tranca o canal.').setDefaultMemberPermissions(PermissionFlagsBits.ManageChannels),async execute(i){await i.channel.permissionOverwrites.edit(i.guild.roles.everyone,{SendMessages:false});await i.reply({embeds:[leonisEmbed({title:'🔒 Canal trancado',description:'O Leonis trancou este canal.',color:COLORS.warning})]})}},
 {data:new SlashCommandBuilder().setName('destrancar').setDescription('Destranca o canal.').setDefaultMemberPermissions(PermissionFlagsBits.ManageChannels),async execute(i){await i.channel.permissionOverwrites.edit(i.guild.roles.everyone,{SendMessages:null});await i.reply({embeds:[leonisEmbed({title:'🔓 Canal aberto',description:'O Leonis destrancou este canal.',color:COLORS.success})]})}},
 {data:new SlashCommandBuilder().setName('cargo-criar').setDescription('Cria um cargo.').setDefaultMemberPermissions(PermissionFlagsBits.ManageRoles).addStringOption(o=>o.setName('nome').setDescription('Nome do cargo').setRequired(true)),async execute(i){const r=await i.guild.roles.create({name:i.options.getString('nome',true),reason:`Leonis: ${i.user.tag}`});await i.reply({embeds:[leonisEmbed({title:'👑 Cargo criado',description:`O cargo ${r} foi criado com sucesso.`,color:COLORS.success})]})}},
 {data:new SlashCommandBuilder().setName('cargo-adicionar').setDescription('Adiciona um cargo a um membro.').setDefaultMemberPermissions(PermissionFlagsBits.ManageRoles).addUserOption(o=>o.setName('usuário').setDescription('Membro').setRequired(true)).addRoleOption(o=>o.setName('cargo').setDescription('Cargo').setRequired(true)),async execute(i){const m=await i.guild.members.fetch(i.options.getUser('usuário',true).id).catch(()=>null);const r=i.options.getRole('cargo',true);if(!m||r.position>=i.guild.members.me.roles.highest.position)return i.reply({content:'❌ Não posso gerenciar esse membro/cargo por causa da hierarquia.',ephemeral:true});await m.roles.add(r,`Leonis: ${i.user.tag}`);await i.reply({embeds:[leonisEmbed({title:'👑 Cargo adicionado',description:`${r} foi adicionado a ${m}.`,color:COLORS.success})]})}},
 {data:new SlashCommandBuilder().setName('cargo-remover').setDescription('Remove um cargo de um membro.').setDefaultMemberPermissions(PermissionFlagsBits.ManageRoles).addUserOption(o=>o.setName('usuário').setDescription('Membro').setRequired(true)).addRoleOption(o=>o.setName('cargo').setDescription('Cargo').setRequired(true)),async execute(i){const m=await i.guild.members.fetch(i.options.getUser('usuário',true).id).catch(()=>null);const r=i.options.getRole('cargo',true);if(!m||r.position>=i.guild.members.me.roles.highest.position)return i.reply({content:'❌ Não posso gerenciar esse membro/cargo por causa da hierarquia.',ephemeral:true});await m.roles.remove(r,`Leonis: ${i.user.tag}`);await i.reply({embeds:[leonisEmbed({title:'👑 Cargo removido',description:`${r} foi removido de ${m}.`,color:COLORS.success})]})}},
];
