import 'dotenv/config';
import { Client, GatewayIntentBits, Partials, Events, Collection } from 'discord.js';
import { actionCommand } from './commands/actions.js';
import { utilityCommands } from './commands/utility.js';
import { moderationCommands } from './commands/moderation.js';
import { adminCommands } from './commands/admin.js';
import { gameCommands } from './commands/games.js';
import { recordMessage, recordMemberEvent, getGuildConfig } from './systems/storage.js';
import { isBlockedInvite } from './systems/security.js';
import { leonisEmbed, COLORS } from './systems/embeds.js';
import { handlePrefixMessage } from './commands/prefix.js';
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent,GatewayIntentBits.GuildModeration],partials:[Partials.Message,Partials.Channel,Partials.GuildMember]});
client.commands=new Collection();
[actionCommand,...utilityCommands,...moderationCommands,...adminCommands,...gameCommands].forEach(c=>client.commands.set(c.data.name,c));
const recentMessages=new Map(),joinBursts=new Map();
client.once(Events.ClientReady,bot=>console.log(`🦁 Leonis online como ${bot.user.tag} • ${client.commands.size} comandos • prefixo ${process.env.PREFIX||'l!'}`));
client.on(Events.MessageCreate,async m=>{if(!m.guild||m.author.bot)return;const c=getGuildConfig(m.guild.id);if(c.security.blockInvites&&isBlockedInvite(m.content)){try{await m.delete();}catch{}recordMessage(m,'blocked-invite');return}if(c.security.antiFlood){const now=Date.now(),key=`${m.guild.id}:${m.author.id}`,e=(recentMessages.get(key)||[]).filter(t=>now-t<8000);e.push(now);recentMessages.set(key,e);if(e.length>=c.security.floodThreshold)try{await m.member.timeout(10000,'Leonis anti-flood')}catch{}}recordMessage(m,'created');try{await handlePrefixMessage(m,client)}catch(e){console.error('Prefix command error:',e);if(m.content.startsWith(process.env.PREFIX||'l!'))await m.reply({embeds:[leonisEmbed({title:'❌ Erro',description:'O Leonis não conseguiu executar esse comando.',color:COLORS.danger})]});}});
client.on(Events.GuildMemberAdd,async m=>{recordMemberEvent(m.guild.id,'join',m.user.id,m.user.tag);const c=getGuildConfig(m.guild.id);if(!c.security.antiRaid)return;const now=Date.now(),e=(joinBursts.get(m.guild.id)||[]).filter(t=>now-t<15000);e.push(now);joinBursts.set(m.guild.id,e);if(e.length>=c.security.joinThreshold)try{await Promise.all(m.guild.channels.cache.map(ch=>ch.isTextBased()?ch.setRateLimitPerUser(10,'Leonis anti-raid'):null))}catch{}});
client.on(Events.GuildMemberRemove,m=>recordMemberEvent(m.guild.id,'leave',m.user?.id??m.id,m.user?.tag??m.id));
client.on(Events.MessageDelete,m=>{if(m.guild)recordMessage(m,'deleted')});
client.on(Events.MessageUpdate,(o,n)=>{if(n.guild&&o.content!==n.content)recordMessage(n,'edited',o.content)});
client.on(Events.InteractionCreate,async i=>{if(!i.isChatInputCommand())return;const c=client.commands.get(i.commandName);if(!c)return;try{await c.execute(i)}catch(e){console.error(e);const p={embeds:[leonisEmbed({title:'❌ Erro',description:'O Leonis tropeçou feio aqui. Tenta novamente.',color:COLORS.danger})],ephemeral:true};if(i.replied||i.deferred)await i.followUp(p);else await i.reply(p)}});
if(!process.env.DISCORD_TOKEN)throw new Error('DISCORD_TOKEN não configurado.');client.login(process.env.DISCORD_TOKEN);
